### ISSUE TITLE
BUG: Running the installation process I have this error

### ISSUE THREAD

**Issue by arturotrenard** [nchia-net/ext9-blockchain#2]
Obtaining file:///home/ext9-blockchain
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/ext9-blockchain/venv/bin/python /home/ext9-blockchain/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpnzotd6i6
         cwd: /home/ext9-blockchain
    Complete output (9 lines):
    running dist_info
    creating /tmp/pip-modern-metadata-cwrfsdcl/chia_blockchain.egg-info
    writing /tmp/pip-modern-metadata-cwrfsdcl/chia_blockchain.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-modern-metadata-cwrfsdcl/chia_blockchain.egg-info/dependency_links.txt
    writing entry points to /tmp/pip-modern-metadata-cwrfsdcl/chia_blockchain.egg-info/entry_points.txt
    writing requirements to /tmp/pip-modern-metadata-cwrfsdcl/chia_blockchain.egg-info/requires.txt
    writing top-level names to /tmp/pip-modern-metadata-cwrfsdcl/chia_blockchain.egg-info/top_level.txt
    writing manifest file '/tmp/pip-modern-metadata-cwrfsdcl/chia_blockchain.egg-info/SOURCES.txt'
    error: package directory 'build_scripts' does not exist
    ----------------------------------------
WARNING: Discarding file:///home/ext9-blockchain. Command errored out with exit status 1: /home/ext9-blockchain/venv/bin/python /home/ext9-blockchain/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpnzotd6i6 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /home/ext9-blockchain/venv/bin/python /home/ext9-blockchain/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpnzotd6i6 Check the logs for full command output.

**Comment by nchia-net** [comment]
this cause by setup.py not updated .  please follow steps to install latest code from gitee
```bash
git clone https://gitee.com/ext9/ext9-blockchain.git -b net9.dev  --recurse-submodules
cd ext9-blockchain
sh install.sh
. ./activate
```

**Comment by nchia-net** [comment]
Known issue, this cause by setup.py not updated. already fixed.
